name: PR Check
on:
  pull_request:
    branches:
      - dev
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:23
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Lint code
        run: npm run lint
      - name: E2E tests
        run: npm run e2e-test
