name: Cypress Tests using Cypress Docker Image
on:
  pull_request:
    branches:
      - dev
jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    container:
      image: cypress/browsers:22.15.0
      options: --user 1001
    steps:
      - name: Cypress run
        uses: cypress-io/github-action@v6
      - name: E2E test
        run: npm run e2e-test
